{{/* Chart base name. */}}
{{- define "studio-gateway.name" -}}
{{- default "studio-gateway" .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Fullname — the base for every resource name, so cluster-scoped objects don't collide
across installs. If the release name already contains the chart name, use it as-is to
avoid "amortized-studio-gateway-studio-gateway".
*/}}
{{- define "studio-gateway.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := include "studio-gateway.name" . -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{/* Service account name. */}}
{{- define "studio-gateway.serviceAccountName" -}}
{{- include "studio-gateway.fullname" . -}}
{{- end -}}

{{/* Serving-cert secret (auto-generated by the OpenShift service-ca operator). */}}
{{- define "studio-gateway.tlsSecretName" -}}
{{- printf "%s-tls" (include "studio-gateway.fullname" .) -}}
{{- end -}}

{{/* oauth-proxy cookie secret. */}}
{{- define "studio-gateway.cookieSecretName" -}}
{{- printf "%s-oauth" (include "studio-gateway.fullname" .) -}}
{{- end -}}

{{- define "studio-gateway.labels" -}}
app: amortized
app.kubernetes.io/name: {{ include "studio-gateway.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
component: gateway
{{- end -}}

{{- define "studio-gateway.selectorLabels" -}}
app: amortized
component: gateway
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
