apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "studio-gateway.serviceAccountName" . }}
  labels:
    {{- include "studio-gateway.labels" . | nindent 4 }}
  annotations:
    # Lets oauth-proxy use this SA as an OAuth client, redirecting back to our Route.
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ include "studio-gateway.fullname" . }}"}}'
